theme: minima
title: “Vista‘s Post 普通的博客网站”
author: Vista醒复醉，中英名字之间并没有什么联系，不如说现实生活中很少有人用这两个名字称呼我，“醉饮东坡醒复醉”
description: 你好，这其实是我第二次创建博客了，因为看不懂英文没发现运行失败的提示，我郁闷加拖延很久之后终于解决了问题，顺带一提，我当初觉得“醒复醉”这个名字很酷，现在我觉得有点傻X


